SET TERMOUT  ON
SET ECHO     OFF
SET FEEDBACK ON
SET VERIFY   ON
SET PAUSE    OFF
SET SQLBLANKLINES ON
set SERVEROUTPUT on size 1000000
WHENEVER SQLERROR CONTINUE

SPOOL XXEAM317.log

PROMPT # PRE INSTALL IS EMPTY

SPOOL OFF
EXIT
